### ISSUE TITLE
[BUG] Cannot read property 'appendBuffer' of null

### ISSUE THREAD

**Issue by nikolaiivanov93** [LdDl/video-server#20]
hi. I have a problem 'appendBuffer' in MsePlayer. Server written in rast. I getting streams in 'arrayBuffer', but i get the error: Cannot read property 'appendBuffer' of null. I need help. I will be grateful for the help.

**Comment by LdDl** [comment]
Hello @nikolaiivanov93 
Is this related to client-side only?
Does this errors prevent video to be played at all?

**Comment by nikolaiivanov93** [comment]
@LdDl Yes it's on the client.  Video does not play.

**Comment by LdDl** [comment]
via Opera:
![image](https://user-images.githubusercontent.com/8864477/132525162-41103185-fc7c-4c23-8237-ad2277142468.png)

via Chrome:
![image](https://user-images.githubusercontent.com/8864477/132525304-8c2dec80-d929-43f4-8dd7-c9138426233e.png)

via Firefox:
![image](https://user-images.githubusercontent.com/8864477/132525566-baa37478-bc7a-4c95-a16e-876c46463682.png)


I guess that something wrong with new version of chrome (mine is 93.0.4577.63 64bit)
Since I'm not JS expert by any means I need more time to investigate this error

**Comment by LdDl** [comment]
I can't reproduce this bug anymore (on commit [79a64744b5fa6f0804401e885640660edf5bf46f](https://github.com/LdDl/video-server/commit/79a64744b5fa6f0804401e885640660edf5bf46f))
Chrome version is: Version 100.0.4896.127 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/8864477/163821371-3a4266e9-3fb9-45c0-8ffa-2d309089f7b8.png)

![image](https://user-images.githubusercontent.com/8864477/163821244-3e71577e-36f8-4b8f-a905-f87df6291cc9.png)

![image](https://user-images.githubusercontent.com/8864477/163821286-822ac4ab-9084-489b-8120-9524e500354a.png)

Reopen the issue if this happens still
